version: '3.7'

services:
  node-app:
    build: ./node-app # Đường dẫn đến thư mục chứa Dockerfile của ứng dụng Node.js
    container_name: node-app-container
    ports:
      - "3000:3000" # Map cổng 3000 của container với cổng 3000 của host
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=mydb
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306" # Map cổng 3306 của container với cổng 3306 của host
    volumes:
      - mysql-data:/var/lib/mysql # Lưu trữ dữ liệu MySQL
    restart: always

volumes:
  mysql-data:
    driver: local
