version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    ports:
      - "8080:80"  # Map cổng 80 của container sang cổng 8080 trên máy host
    environment:
      WORDPRESS_DB_HOST: mysql:3306  # Địa chỉ của dịch vụ MySQL
      WORDPRESS_DB_NAME: wordpress   # Tên database cho WordPress
      WORDPRESS_DB_USER: root        # Username của MySQL
      WORDPRESS_DB_PASSWORD: example # Mật khẩu của MySQL
    volumes:
      - wordpress-data:/var/www/html  # Volume để lưu trữ dữ liệu của WordPress
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: example   # Đặt mật khẩu root cho MySQL
      MYSQL_DATABASE: wordpress      # Tạo database cho WordPress
      MYSQL_USER: user               # Tạo user cho MySQL
      MYSQL_PASSWORD: example        # Mật khẩu của user
    volumes:
      - mysql-data:/var/lib/mysql     # Volume để lưu trữ dữ liệu MySQL
    restart: always

volumes:
  wordpress-data:
    driver: local
  mysql-data:
    driver: local
